//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalData
    {
        public int Id { get; set; }
        public int IdTypeBody { get; set; }
        public int CountDoor { get; set; }
        public int IdTypeEngine { get; set; }
        public string LocationEngine { get; set; }
        public Nullable<decimal> WorkScopeEngine { get; set; }
        public int CodeProduct { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TypeBody TypeBody { get; set; }
        public virtual TypeEngine TypeEngine { get; set; }
    }
}
